#! /bin/bash

cmd="$0"
if [ -L "${cmd}" ]
then
    cmd="$(readlink $cmd)"
fi
projectdir="$(dirname $cmd)"
targetdir="${projectdir}/target"
classesdir="${targetdir}/classes"
currentdir="${PWD}"

#obtains classes/
if [ ! -d "${classesdir}" ]
then
    cd "${projectdir}"
    mvn compile
    cd "${currentdir}"
fi

#obtains path to asm.jar
asmpathfile="${targetdir}/mvn-exec-cp.txt"
if [ ! -f "${asmpathfile}" ]
then
    cd "${projectdir}"
    mvn dependency:build-classpath -DincludeArtifactIds=asm -Dmdep.outputFile="${asmpathfile}"
    cd "${currentdir}"
fi
asmpath=$(cat "${asmpathfile}" | tr '[:space:]' ':')

java ${MAVEN_EXEC_JAVA_OPTS} -cp "${classesdir}:${asmpath}" org.autogui.exec.MavenExecJava "$@"
