#! /bin/bash

cmd="$0"
if [ -L "${cmd}" ]
then
    cmd="$(readlink $cmd)"
fi
projectdir="$(dirname $cmd)"
targetdir="${projectdir}/target"
moddir="${targetdir}/mods"
currentdir="${PWD}"

#obtains target/mods
if [ ! -d "${moddir}" ]
then
    cd "${projectdir}"
    mvn clean package dependency:copy-dependencies "-DoutputDirectory=${moddir}"
    cp "$targetdir"/mvn-exec-*.jar "${moddir}"
    cd "${currentdir}"
fi

java ${MAVEN_EXEC_JAVA_OPTS} -p "${moddir}" -m "org.autogui.mvn_exec" "$@"
